apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaobject-agents
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metaobject-agents
  template:
    metadata:
      labels:
        app: metaobject-agents
    spec:
      containers:
      - name: rails
        image: gcr.io/your-project/metaobject-agents:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: MEMCACHED_SERVERS
          value: "memcached-service:11211"
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: project-id
        - name: SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: shopify-credentials
              key: api-key
        - name: SHOPIFY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: shopify-credentials
              key: api-secret
        - name: SHOPIFY_SHOP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: shopify-credentials
              key: shop-domain
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: metaobject-agents-service
spec:
  selector:
    app: metaobject-agents
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP